export const labelMap: { [key: number]: string } = {
    1: "nhà lầu",
    2: "nhà mái ngói",
    3: "nhà rông",
    4: "nhà sàn",
    5: "nhà biệt thự",
    6: "nhà trên cây",
    7: "nhà gỗ",
    8: "nhà chung cư",
    9: "nhà trệt",
    10: "nhà kí túc xá",
    11: "ti vi",
    12: "đèn",
    13: "đồng hồ",
    14: "cầu thang",
    15: "chìa khóa",
    16: "ổ khóa",
    17: "bàn ghế sofa",
    18: "bàn thờ",
    19: "điện thoại bàn",
    20: "tranh ảnh treo tường",
    21: "kệ sách",
    22: "cái chảo",
    23: "cái ấm",
    24: "con dao",
    25: "máy say sinh tố",
    26: "tủ lạnh",
    27: "nồi",
    28: "bếp ga",
    29: "muỗng",
    30: "đôi đũa",
    31: "bát",
    32: "giường",
    33: "quạt",
    34: "máy tính",
    35: "bàn là",
    36: "rèm",
    37: "thước kẻ",
    38: "cái kéo",
    39: "com pa",
    40: "cục tẩy",
    41: "hồ dán",
    42: "bút chì",
    43: "bút bi",
    44: "bảng phấn",
    45: "viên phấn",
    46: "gọt bút chì",
    47: "sữa chua",
    48: "cà phê",
    49: "nước uống",
    50: "bánh mì",
    51: "bún",
    52: "mì quảng",
    53: "xôi",
    54: "phở",
    55: "cháo",
    56: "trứng ốp la",
    57: "nắng",
    58: "mặt trời",
    59: "mây",
    60: "gió",
    61: "nóng",
    62: "mát",
    63: "lạnh",
    64: "nhiệt độ",
    65: "tuyết",
    66: "sương mù",
    67: "thợ xây",
    68: "thợ làm móng",
    69: "cắt tóc",
    70: "sửa xe",
    71: "thợ sơn",
    72: "đường bộ",
    73: "đường sắt",
    74: "đường thủy",
    75: "đường hàng không",
    76: "cáp treo",
    77: "máy bay",
    78: "cano cao tốc",
    79: "xe máy",
    80: "xe đạp",
    81: "xe buýt",
    82: "thuyền buồm",
    83: "xe cảnh sát",
    84: "xe mô tô",
    85: "tàu hỏa",
    86: "xe tải",
    87: "xe hơi",
    88: "xích lô",
    89: "khinh khí cầu",
    90: "xe cứu hỏa",
    91: "tàu điện ngầm",
    92: "con chó",
    93: "con mèo",
    94: "con cá",
    95: "con chuột",
    96: "con rùa",
    97: "con chim",
    98: "con bò",
    99: "con gà",
    100: "con ngựa",
    101: "con heo",
    102: "con lừa",
    103: "con dê",
    104: "con trâu",
    105: "con ong",
    106: "con tôm",
    107: "bơi",
    108: "cầu trượt",
    109: "chạy",
    110: "thả diều",
    111: "nhảy dây",
    112: "đá cầu",
    113: "đá bóng",
    114: "câu cá",
    115: "cắm trại",
    116: "kéo co",
    117: "con lừa",
    118: "máy ảnh",
    119: "mũ lưỡi trai",
    120: "ống nhòm"
};
